# This workflow will build a package using Maven

name: Build Maven Package

on:
  push:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'

    - name: Build with Maven
      run: |
        sudo apt install maven
        mvn -B package --file pom.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: build-jar
        path: /home/runner/work/auto-deploy-spring/auto-deploy-spring/target/basic-0.0.1-SNAPSHOT.jar

